/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qtfreet_yunbo_jni_jni */

#ifndef _Included_com_qtfreet_yunbo_jni_jni
#define _Included_com_qtfreet_yunbo_jni_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qtfreet_yunbo_jni_jni
 * Method:    API
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qtfreet_yunbo_jni_jni_API
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
